apiVersion: apps/v1
kind: Deployment
metadata:
    name: app1
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app1
    template:
        metadata:
            labels:
                app: app1
        spec:
            containers:
            - name: app1
              image: rancher/hello-world
              ports:
                  - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: app1-svc
spec:
    ports:
    - name: http
      port: 80
    selector:
        app: app1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: app1-svc
                port: 
                    number: 80
---
apiVersion: v1
kind: Service
metadata:
    name: traefik-ingress-service
    namespace: kube-system
spec:
    type: NodePort
    ports:
    - name: traefik
      port: 80
      nodePort: 30182
      targetPort: 80
    selector:
        app: traefik
