apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-one
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-one
    template:
        metadata:
            labels:
                app: app-one
        spec:
            containers:
            - name: app-one
              image: rancher/hello-world
              env:
              - name: MESSAGE
                value: "Hello from app1."
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: app-one
spec:
    ports:
    - name: http
      port: 80
    selector:
        app: app-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-two
spec:
    replicas: 3
    selector:
        matchLabels:
            app: app-two
    template:
        metadata:
            labels:
                app: app-two
        spec:
            containers:
            - name: app-two
              image: rancher/hello-world
              env:
              - name: MESSAGE
                value: "Hello from app2."
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: app-two
spec:
    ports:
    - name: http
      port: 80
    selector:
        app: app-two
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-three
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-three
    template:
        metadata:
            labels:
                app: app-three
        spec:
            containers:
            - name: app-three
              image: rancher/hello-world
              env:
              - name: MESSAGE
                value: "Hello from app3."
              ports:
              - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: app-three
spec:
    ports:
    - name: http
      port: 80
    selector:
        app: app-three
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: app-one
                port: 
                    number: 80
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: app-two
                port: 
                    number: 80
  - host: app3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: app-three
                port: 
                    number: 80
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
            service:
                name: app-three
                port: 
                    number: 80
