IMAGE = "centos/8"
MEM = 1024
CPU = 1
MASTER_NAME = "ramoukhaS"
MASTER_IP = "192.168.42.110"

Vagrant.configure("2") do |config|

	config.vm.box = IMAGE
	config.vm.provider "virtualbox" do |vb|
		vb.memory = MEM
		vb.cpus = CPU
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define MASTER_NAME do |master|
		master.vm.hostname = MASTER_NAME
		master.vm.network :private_network, ip: MASTER_IP
		master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
		master.vm.provision "file", source: "./confs/apps_config.yaml", destination: "/tmp/apps_config.yaml"
		master.vm.provision "shell", privileged: true, path: "scripts/master_install.sh"
		master.vm.provider "virtualbox" do |v|
			v.name = MASTER_NAME
		end
	end

end
