IMAGE = "centos/8"
MEM = 1024
CPU = 1
MASTER_NAME = "ramoukhaS"
WORKER_NAME = "zoulhafiSW"
MASTER_IP = "192.168.42.110"
WORKER_IP = "192.168.42.111"

Vagrant.configure("2") do |config|

	config.vm.box = IMAGE
	config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = MEM
		vb.cpus = CPU
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
	end

	config.vm.define MASTER_NAME do |master|
		master.vm.hostname = MASTER_NAME
		master.vm.network :private_network, ip: MASTER_IP
		master.vm.provision "shell", privileged: true, path: "scripts/master_install.sh"
		master.vm.provider "virtualbox" do |v|
			v.name = MASTER_NAME
		end
		master.trigger.after :up do |trigger|
			trigger.run = { inline: "scp -o StrictHostKeyChecking=no root@#{MASTER_IP}:/var/lib/rancher/k3s/server/token token" }
		end
		master.trigger.after :up do |trigger|
			trigger.run = { inline: "scp -o StrictHostKeyChecking=no root@#{MASTER_IP}:/etc/rancher/k3s/k3s.yaml k3s.yaml" }
		end
	end

	config.vm.define WORKER_NAME do |worker|
		worker.vm.hostname = WORKER_NAME
		worker.vm.network :private_network, ip: WORKER_IP 
		worker.vm.provision "file", source: "token", destination: "/tmp/token"
		worker.vm.provision "file", source: "k3s.yaml", destination: "/tmp/k3s.yaml"
		worker.vm.provision "shell", privileged: true, path: "scripts/worker_install.sh"
		worker.vm.provider "virtualbox" do |v|
			v.name = WORKER_NAME
		end
		worker.trigger.after :destroy do |trigger|
			trigger.run = { inline: "rm -f k3s.yaml token" }
		end
	end

end
